#! /usr/bin/env python
##########################################################################
# CAPSUL - Copyright (C) CEA, 2013
# Distributed under the terms of the CeCILL-B license, as published by
# the CEA-CNRS-INRIA. Refer to the LICENSE file or to
# http://www.cecill.info/licences/Licence_CeCILL-B_V1-en.html
# for details.
##########################################################################

import logging
import sys

from capsul.apps_qt import qt_backend
qt_backend.set_qt_backend()
QtCore = qt_backend.QtCore

try :
    from capsul.apps_qt.pipeline_viewer_app import PipelineViewerApp
    app = PipelineViewerApp()

except :
    import sys
    import traceback

    exc_info = sys.exc_info()
    trace = "".join(traceback.format_exception(*exc_info))

    logging.error(trace)

else :
    QtCore.QObject.connect(app, QtCore.SIGNAL('lastWindowClosed()'), 
                           app, QtCore.SLOT('quit()'))
    sys.exit(app.exec_())

