language: python

python:
    - 2.6
    - 2.7

before_install:
    - sudo apt-get update
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.6.0-Linux-x86_64.sh -O miniconda.sh; fi
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - hash -r

install:
    - conda update --yes conda
    - conda create -n testenv --yes pip python=$TRAVIS_PYTHON_VERSION
    - source activate testenv
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install ordereddict; fi
    - conda install --yes numpy scipy nose traits networkx dateutil
    - pip install argparse
    - pip install importlib
    - pip install nibabel
    - pip install nose-cov
    - pip install nipype
    - pip install xmltodict
    - pip install soma-workflow
    - python setup.py install

script:
    - python test/test_capsul.py


