exclude = [
  "sphinxext",
]

[lint]
extend-select = [
  "B",   # https://docs.astral.sh/ruff/rules/#flake8-bugbear
  "I",   # https://docs.astral.sh/ruff/rules/#isort-i
  "UP",  # https://docs.astral.sh/ruff/rules/#pyupgrade-up
]
ignore = [
  # FIXME: apply the following rules
  "B007",
  "B023",
  "B026",
  "F401",
  "F841",
  "E402",
  "E741",
  "E501",
  "UP015",
  "UP030",
  "UP031",
  "UP032",
  # https://docs.astral.sh/ruff/rules/redundant-open-modes/
  # we prefer explicit to implicit open modes
  "UP015",
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191",
  "E111",
  "E114",
  "E117",
  "D206",
  "D300",
  "Q000",
  "Q001",
  "Q002",
  "Q003",
  "COM812",
  "COM819",
  "ISC001",
  "ISC002",
]
